project:
  type: website
  output-dir: docs

website:
  title: "portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mfehr34
      - icon: linkedin
        href: https://www.linkedin.com/in/mitchell-fehr-491394292
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

